# Build data sheet from asciidoc sources

name: 'Build Data Sheet'

on:
  push:
    branches:
    - master
    paths:
    - 'docs/src_adoc/**'
  pull_request:
    branches:
    - master
    paths:
    - 'docs/src_adoc/**'
  workflow_dispatch:

jobs:

  asciidoc_build:
    runs-on: ubuntu-latest
    name: Build Asciidoc
    steps:
      - name: 'ðŸ§° Repository Checkout'
        uses: actions/checkout@v2

      - name: 'ðŸ“š Build PDF'
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -a pdf-theme=docs/src_adoc/neorv32-theme.yml docs/src_adoc/neorv32.adoc --out-file docs/NEORV32.pdf"

      - name: 'ðŸš€ Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: NEORV32.pdf
          path: docs/NEORV32.pdf
