name: Implementation

on:
  push:
    paths:
    - 'setups/**'
    - 'rtl/**'
  pull_request:
    paths:
    - 'setups/**'
    - 'rtl/**'
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  all-in-one:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {
            board: UPduino_v3,
            design: 'MinimalBoot',
            bitstream: neorv32_UPduino_v3_MinimalBoot.bin
          }
          - {
            board: UPduino_v3,
            design: 'UP5KDemo',
            bitstream: neorv32_UPduino_v3_UP5KDemo.bin
          }
          - {
            board: Fomu,
            design: 'MinimalBoot',
            bitstream: neorv32_Fomu_pvt_MinimalBoot.bit
          }
    name: 'üõ≥Ô∏è All-in-one | ${{ matrix.board }} | ${{ matrix.design }}'
    env:
      GHDL_PLUGIN_MODULE: ghdl

    steps:

    - name: 'üß∞ Repository Checkout'
      uses: actions/checkout@v2

    - name: '‚öôÔ∏è Generate ${{ matrix.board }} ${{ matrix.design }} bitstream'
      uses: docker://ghcr.io/hdl/debian-buster/impl
      with:
        args: make -C setups/examples BOARD=${{ matrix.board }} ${{ matrix.design }}

    - name: 'üì§ Upload Artifact: ${{ matrix.board }} ${{ matrix.design }} bitstream and reports'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.board }}-${{ matrix.design }}
        path: |
          setups/examples/${{ matrix.bitstream }}
          setups/osflow/${{ matrix.board }}/*-report.txt
