name: Implementation

on:
  push:
    paths:
    - 'boards/**'
    - 'rtl/**'
  pull_request:
    paths:
    - 'boards/**'
    - 'rtl/**'
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  all-in-one:
    runs-on: ubuntu-latest
    name: 'ğŸ›³ï¸ All-in-one'
    env:
      GHDL_PLUGIN_MODULE: ghdl

    steps:

    - name: 'ğŸ§° Repository Checkout'
      uses: actions/checkout@v2

    - name: 'âš™ï¸ Generate bitstream'
      uses: docker://ghcr.io/hdl/debian-buster/impl
      with:
        args: make -C boards/osflow/UPduino_v3/ all

    - name: 'ğŸ“¤ Upload Artifact: bitstream'
      uses: actions/upload-artifact@v2
      with:
        name: UPduino_v3
        path: |
          boards/osflow/UPduino_v3/neorv32_upduino_v3_impl_1.bin
          boards/osflow/UPduino_v3/*-report.txt
