# Run the RISC-V compliance framework port to check current NEORV32 version
name: 'RISC-V Compliance Test'

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: 'üêß Linux'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Get gcc toolchain
      - name: 'Install RISC-V GCC Toolchain'
        run: /bin/bash -c "chmod u+x ./.ci/install.sh && ./.ci/install.sh"

      # Get GHDL simulator
      - name: 'Setup GHDL'
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: gcc

      # Run compliance test framework
      - name: 'Setup GHDL'
        run: /bin/bash -c "chmod u+x ./riscv-compliance/run_compliance_test.sh && ././riscv-compliance/run_compliance_test.sh"
