# Run the RISC-V riscv-arch-test test framework port to check current NEORV32 version

name: 'riscv-arch-test'

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
        - I
        - C
        - M
        - privilege
        - Zifencei
    name: 'RISC-V Compatibility Check'

    steps:

      - name: 'ðŸ§° Repository Checkout'
        uses: actions/checkout@v2

      - name: 'ðŸ”§ Setup Environment Variables'
        run: |
          echo "$GITHUB_WORKSPACE/riscv/bin" >> $GITHUB_PATH
          echo $GITHUB_WORKSPACE

      - name: 'ðŸ”§ Setup RISC-V GCC and doit'
        run: |
          mkdir riscv
          curl -fsSL https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-2.0.0/riscv32-unknown-elf.gcc-10.2.0.rv32i.ilp32.newlib.tar.gz | \
          tar -xzf - -C riscv
          ls -al riscv

          pip3 install doit

      - name: 'ðŸ”§ Setup GHDL Simulator'
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: gcc

      - name: 'ðŸš§ Run RISC-V Architecture Tests'
        run: ./do.py RunRISCVArchitectureTests -s ${{ matrix.suite }}
