# Check NEORV32 software framework and test processor using cpu_test program

name: 'SW & HW Test'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - releases/*
  pull_request:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: '‚öôÔ∏è SW & HW Test'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'üíæ Checkout'
        uses: actions/checkout@v2

      # Setup system env variables
      - name: 'üîß Setup Environment Variables'
        run: |
          echo "$GITHUB_WORKSPACE/riscv/bin" >> $GITHUB_PATH
          echo $GITHUB_WORKSPACE

      # Get gcc toolchain
      - name: 'üîß Setup RISC-V GCC'
        run: |
          /bin/bash -c "chmod u+x ./.ci/install.sh && ./.ci/install.sh"
          echo $GITHUB_WORKSPACE

      # Get GHDL simulator
      - name: 'üîß Setup GHDL'
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: gcc

      # Get gcc toolchain
      - name: 'üîß Check Environment Variables'
        run: echo $PATH
  
      # Run software framework tests
      - name: '‚ñ∂Ô∏è Run SW Tests'
        run: /bin/bash -c "chmod u+x ./.ci/sw_check.sh && ./.ci/sw_check.sh"
  
      # Run hardware fremwork tests
      - name: '‚ñ∂Ô∏è Run HW Tests'
        run: /bin/bash -c "chmod u+x ./.ci/hw_check.sh && ./.ci/hw_check.sh"
